package com.example.shining.p044_wechat_record.greendaoset.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.shining.p044_wechat_record.audiomanagerset.domain.Recorder;

import com.example.shining.p044_wechat_record.greendaoset.greendao.RecorderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recorderDaoConfig;

    private final RecorderDao recorderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recorderDaoConfig = daoConfigMap.get(RecorderDao.class).clone();
        recorderDaoConfig.initIdentityScope(type);

        recorderDao = new RecorderDao(recorderDaoConfig, this);

        registerDao(Recorder.class, recorderDao);
    }
    
    public void clear() {
        recorderDaoConfig.getIdentityScope().clear();
    }

    public RecorderDao getRecorderDao() {
        return recorderDao;
    }

}
